import AnimatedText from '@/components/AnimatedText'
import Education from '@/components/Education'
import Experience from '@/components/Experience'
import Layout from '@/components/Layout'
import Skills from '@/components/Skills'
import Transition from '@/components/Transition'
import { useInView, useMotionValue, useSpring } from 'framer-motion'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef } from 'react'
import profilepic from '../../public/images/profile/developer-pic-2.jpg'

const AnimatedNumbers = ({ value }) => {
  const ref = useRef(null)

  const motionValue = useMotionValue(0)
  const springValue = useSpring(motionValue, { duration: 3000 })
  const isInView = useInView(ref, { once: true })

  useEffect(() => {
    if (isInView) {
      motionValue.set(value)
    }
  }, [value, motionValue, isInView])

  useEffect(() => {
    springValue.on('change', (latestValue) => {
      if (ref.current && latestValue.toFixed(0) <= value) {
        ref.current.textContent = latestValue.toFixed(0)
      }
    })
  }, [springValue, value])

  return <span ref={ref}></span>
}

const about = () => {
  return (
    <>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Transition />

      <main className="w-full flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Passion Fuels Purpose! "
            className="text-7xl mb-16 lg:text-6xl pt-6"
          />
          <div className="w-full grid grid-cols-8  gap-16">
            <div className="col-span-3 flex flex-col justify-start items-start xl:col-span-4 md:col-span-8 md:order-2">
              <h2 className=" uppercase font-bold text-dark/75 text-lg dark:text-light/75">
                Biography
              </h2>

              <p className=" font-medium my-4 dark:text-light">
                Hi, I'm CodeBucks , a web developer and UI/UX designer with a
                passion for creating beautiful, functional, and user-centered
                digital experiences. With 4 years of experience in the field. I
                am always looking for new and innovative ways to bring my
                clients' visions to life.
              </p>
              <p className=" font-medium my-4 dark:text-light">
                I believe that design is about more than just making things look
                pretty – it's about solving problems and creating intuitive,
                enjoyable experiences for users.{' '}
              </p>
              <p className=" font-medium my-4 dark:text-light">
                Whether I'm working on a website, mobile app, or other digital
                product, I bring my commitment to design excellence and
                user-centered thinking to every project I work on. I look
                forward to the opportunity to bring my skills and passion to
                your next project.
              </p>
            </div>

            <div className="col-span-3 w-full h-max border-2 border-solid border-dark  bg-light rounded-2xl p-6 relative xl:col-span-4 dark:bg-dark dark:border-light md:col-span-8 md:order-1 ">
              <Image
                src={profilepic}
                alt="profile pic"
                className="w-full h-auto rounded-2xl "
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                priority={true}
              />
              <div className="absolute top-0 -right-3 w-[102%] h-[103%]   -z-10   bg-dark rounded-[2rem] dark:bg-light" />
            </div>

            <div className=" col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row md:order-3 ">
              <div className="flex flex-col items-end justify-center">
                <span className=" inline-block text-7xl font-bold dark:text-light md:text-5xl">
                  <AnimatedNumbers value={40} />+
                </span>
                <h2 className="font-medium text-dark/75 text-lg capitalize dark:text-light/75 md:text-sm">
                  Satisfied client
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className=" inline-block text-7xl font-bold  dark:text-light md:text-5xl">
                  <AnimatedNumbers value={50} />+
                </span>
                <h2 className="font-medium text-dark/75 text-lg capitalize  dark:text-light/75 md:text-sm">
                  Projects completed
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className=" inline-block text-7xl font-bold  dark:text-light md:text-5xl">
                  <AnimatedNumbers value={4} />+
                </span>
                <h2 className="font-medium text-dark/75 text-lg capitalize  dark:text-light/75 md:text-sm">
                  Years of experience
                </h2>
              </div>
            </div>
          </div>
          <Skills />
          <Experience />
          <Education />
        </Layout>
      </main>
    </>
  )
}
export default about
