import AnimatedText from '@/components/AnimatedText'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import articleImg1 from '../../public/images/articles/pagination component in reactjs.jpg'

import { motion, useMotionValue } from 'framer-motion'
import { useRef } from 'react'
import Transition from '@/components/Transition'

const FramerImage = motion(Image)

const MovingImg = ({ img, link, text }) => {
  const x = useMotionValue(0)
  const y = useMotionValue(0)

  const imgRef = useRef(null)

  const onMouseHover = (e) => {
    imgRef.current.style.display = 'inline-block'
    x.set(e.pageX)
    y.set(-10)
  }

  const onMouseLeave = (e) => {
    imgRef.current.style.display = 'none'
    x.set(0)
    y.set(0)
  }

  return (
    <Link href={link} target="_blank">
      <div
        className="font-semibold text-xl dark:text-light"
        onMouseMove={onMouseHover}
        onMouseLeave={onMouseLeave}
      >
        {text}
      </div>
      <FramerImage
        ref={imgRef}
        initial={{
          opacity: 0,
        }}
        whileInView={{
          opacity: 1,
        }}
        transition={{
          duration: 0.25,
        }}
        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        src={img}
        alt="articleimg"
        className="w-96 h-auto absolute hidden rounded-lg"
        style={{ x: x, y: y }}
      />
    </Link>
  )
}

const Article = ({ img, link, time, text }) => {
  return (
    <motion.div
      initial={{ y: 200 }}
      whileInView={{ y: 0, transition: { duration: 0.5, ease: 'easeInOut' } }}
      viewport={{ once: true }}
      className="w-full flex items-center justify-between px-6 py-6 border-2 border-solid border-dark dark:border-light rounded-xl border-r-4 border-b-4 hover:underline md:flex-col md:items-start md:gap-2"
    >
      <MovingImg img={img} link={link} text={text} />
      <div className="text-primary font-medium text-lg dark:text-primaryDark">
        {time}
      </div>
    </motion.div>
  )
}

const FeaturedArticle = ({ img, title, time, summary, link }) => {
  return (
    <li className=" relative w-full flex flex-col items-center justify-between border-2 border-dark bg-light dark:border-light dark:bg-dark shadow-2xl border-solid rounded-3xl p-6 md:col-span-2">
      <div className="absolute top-0 -right-3 w-[100%] h-[103%] -z-10   bg-dark rounded-[2rem] dark:bg-light" />
      <Link
        href={link}
        target="_blank"
        className="cursor-pointer overflow-hidden rounded-2xl"
      >
        <FramerImage
          src={img}
          alt="Projecty img"
          className="w-full h-auto rounded-lg overflow-hidden "
          whileHover={{ scale: 1.05 }}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
      </Link>
      <div className=" w-full flex flex-col items-start justify-between ml-4">
        <h3 className="my-2 font-bold text-3xl text-dark hover:underline  dark:text-light lg:text-2xl">
          {title}
        </h3>

        <div className="font-medium  dark:text-light">{summary}</div>

        <span className="font-semibold text-primary  dark:text-primaryDark">
          {time}
        </span>
      </div>
    </li>
  )
}

const articles = () => {
  return (
    <>
      <Head>
        <title>Projects page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />

      <main className="w-full flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Words Can Change The World!"
            className="md:!text-5xl md:pt-8 md:pb-8 my-16"
          />

          <ul className="w-full grid grid-cols-2  gap-16 mb-16">
            <FeaturedArticle
              img={articleImg1}
              title="Build A Custom Pagination Component In Reactjs From Scratch"
              time="9 min read"
              summary="earn how to build a custom pagination component in ReactJS from scratch. 
Follow this step-by-step guide to integrate Pagination component in your ReactJS project."
              link="/"
            />
            <FeaturedArticle
              img={articleImg1}
              title="Build A Custom Pagination Component In Reactjs From Scratch"
              time="9 min read"
              summary="earn how to build a custom pagination component in ReactJS from scratch. 
Follow this step-by-step guide to integrate Pagination component in your ReactJS project."
              link="/"
            />
          </ul>

          <h2 className="font-bold text-black text-4xl text-center my-16 dark:text-light">
            All Articles
          </h2>

          <ul className="w-full flex flex-col items-start justify-between gap-4 mb-32">
            <Article
              text="Form Validation In Reactjs: Build A Reusable Custom Hook For Inputs And Error Handling"
              time="January 27 , 2023"
              img={articleImg1}
              link="/"
            />
            <Article
              text="Silky Smooth Scrolling In Reactjs: A Step-By-Step Guide For React Developers"
              time="January 27 , 2023"
              img={articleImg1}
              link="/"
            />
            <Article
              text="Creating An Efficient Modal Component In React Using Hooks And Portals"
              time="January 27 , 2023"
              img={articleImg1}
              link="/"
            />
            <Article
              text="Build A Fabulous Todo List App With React, Redux And Framer-Motion"
              time="January 27 , 2023"
              img={articleImg1}
              link="/"
            />
            <Article
              text="Redux Simplified: A Beginner's Guide For Web Developers"
              time="January 27 , 2023"
              img={articleImg1}
              link="/"
            />
          </ul>
        </Layout>
      </main>
    </>
  )
}
export default articles
