import AnimatedText from '@/components/AnimatedText'
import HireMe from '@/components/HireMe'
import { LinkArrow } from '@/components/Icons'
import Layout from '@/components/Layout'
import Transition from '@/components/Transition'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import lightBuilb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className="flex items-center text-black min-h-screen dark:bg-dark dark:text-light">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full lg:flex-col pt-8">
            <div className="w-1/2 lg:w-full">
              <Image
                src={profilePic}
                alt="My-pic"
                className=" w-full h-auto lg:hidden md:inline-block"
                priority={true}
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
              />
            </div>
            <div className="w-1/2 lg:w-full">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design. "
                className="!text-6xl !text-left dark:text-light xl:!text-5xl lg:!text-center lg:!text-5xl xs:!text-2xl"
              />
              <p className="font-medium my-2 text-base lg:!text-center xs:!text-sm ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development
              </p>

              <div className="w-full flex items-center self-start mt-2 lg:justify-center">
                <Link
                  href="/dummy.pdf"
                  className=" flex items-center font-bold text-light my-2 bg-dark py-2 px-6 rounded-lg text-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent
                   hover:border-dark dark:bg-light dark:text-dark hover:dark:border-light hover:dark:bg-dark hover:dark:text-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className="ml-2 " />
                </Link>
                <Link
                  href="mailto:abce@gmail.com"
                  className="underline text-dark ml-4 text-lg text-black font-medium dark:text-light underline-offset-4"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className="absolute right-8 bottom-8 md:hidden ">
          <Image src={lightBuilb} alt="Light" className=" w-28" />
        </div>
      </main>
    </>
  )
}
