import AnimatedText from '@/components/AnimatedText'
import { GithubIcon } from '@/components/Icons'
import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import cryptoCurrImg from '../../public/images/projects/crypto-screener-cover-image.jpg'
import project2 from '../../public/images/projects/nft-collection-website-cover-image.jpg'
import { motion } from 'framer-motion'
import Transition from '@/components/Transition'

const FramerImage = motion(Image)

const FeaturedProject = ({ type, title, summary, img, link, github }) => {
  return (
    <article className="relative w-full flex items-center justify-between border-2 border-dark bg-light shadow-2xl border-solid rounded-3xl p-12 dark:border-light dark:bg-dark lg:flex-col ">
      <div className="absolute top-0 -right-3 w-[100%] h-[103%] -z-10   bg-dark rounded-[2rem] dark:bg-light " />
      <Link
        href="/"
        target="_blank"
        className="w-1/2 cursor-pointer overflow-hidden rounded-2xl lg:w-full"
      >
        <FramerImage
          src={img}
          alt="Projecty img"
          className="w-full h-auto rounded-lg overflow-hidden "
          whileHover={{ scale: 1.05 }}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        />
      </Link>
      <div className="w-1/2 flex flex-col items-start justify-between ml-4 lg:w-full">
        <span className="my-2 capitalize text-primary font-medium text-2xl dark:text-primaryDark">
          {type}
        </span>
        <h3 className="my-2 font-bold text-4xl text-dark hover:underline dark:text-light">
          {title}
        </h3>
        <p className="my-2 font-medium dark:text-light">{summary}</p>

        <div className="flex items-center my-2 gap-2 ">
          <Link target="_blank" href={github} className="w-10">
            <GithubIcon className="dark:text-light" />
          </Link>

          <Link
            target="_blank"
            href={link}
            className="py-3 px-6 bg-dark text-light dark:bg-light dark:text-dark rounded-2xl font-semibold text-1xl"
          >
            visit project
          </Link>
        </div>
      </div>
    </article>
  )
}

const Project = ({ type, title, img, link, github }) => {
  return (
    <article className=" relative w-full flex flex-col items-center justify-between border-2 border-dark bg-light shadow-2xl border-solid rounded-3xl p-6 dark:border-light dark:bg-dark">
      <div className="absolute top-0 -right-3 w-[100%] h-[103%] -z-10   bg-dark rounded-[2rem]  dark:bg-light" />
      <Link
        href="/"
        target="_blank"
        className="cursor-pointer overflow-hidden rounded-2xl"
      >
        <FramerImage
          src={img}
          alt="Projecty img"
          className="w-full h-auto rounded-lg overflow-hidden "
          whileHover={{ scale: 1.05 }}
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
          priority={true}
        />
      </Link>
      <div className=" w-full flex flex-col items-start justify-between">
        <span className="my-2 capitalize text-primary font-medium text-1xl dark:text-primaryDark">
          {type}
        </span>
        <h3 className="my-2 font-bold text-3xl text-dark hover:underline dark:text-light">
          {title}
        </h3>

        <div className="w-full flex items-center justify-between my-2 ">
          <Link
            target="_blank"
            href={link}
            className="font-medium text-2xl underline dark:text-light"
          >
            visit
          </Link>
          <Link target="_blank" href={github} className="w-10">
            <GithubIcon className=" dark:text-light" />
          </Link>
        </div>
      </div>
    </article>
  )
}

const projects = () => {
  return (
    <>
      <Head>
        <title>Projects page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Transition />
      <main className="w-full flex flex-col items-center justify-center">
        <Layout className="pt-16">
          <AnimatedText
            text="Imagination Trumps Knowledge! "
            className="md:!text-5xl md:pt-8"
          />

          <div className="w-full grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0 pt-8">
            <div className="col-span-12">
              <FeaturedProject
                type="Featured Project"
                title="Crypto Screener Application"
                summary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency."
                img={cryptoCurrImg}
                link="/"
                github="/"
              />
            </div>
            <div className="col-span-6 md:col-span-12">
              <Project
                type="Website template"
                title="NFT Collection Website"
                img={project2}
                link="/"
                github="/"
              />
            </div>
            <div className="col-span-6 md:col-span-12">
              <Project
                type="Website template"
                title="NFT Collection Website"
                img={project2}
                link="/"
                github="/"
              />
            </div>
            <div className="col-span-12">
              <FeaturedProject
                type="Featured Project"
                title="Crypto Screener Application"
                summary="A feature-rich Crypto Screener App using React, Tailwind CSS, Context API, React Router and Recharts. 
It shows detail regarding almost all the cryptocurrency. You can easily convert the price in your 
local currency."
                img={cryptoCurrImg}
                link="/"
                github="/"
              />
            </div>
            <div className="col-span-6 md:col-span-12">
              <Project
                type="Website template"
                title="NFT Collection Website"
                img={project2}
                link="/"
                github="/"
              />
            </div>
            <div className="col-span-6 md:col-span-12">
              <Project
                type="Website template"
                title="NFT Collection Website"
                img={project2}
                link="/"
                github="/"
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
export default projects
